RELEASES = ["3.0", "3.1", "3.1.1"]
CURRENT_RELEASE = "3.1.1"

HGDP_TGP_RELEASES = ["3.1"]
CURRENT_HGDP_TGP_RELEASE = "3.1"

META_VERSIONS = ["3", "3.1"]
CURRENT_META_VERSION = "3.1"

PROJECT_META_VERSIONS = ["3", "3.1"]
CURRENT_PROJECT_META_VERSION = "3.1"

ANNOTATION_VERSIONS = ["3", "3.1"]
CURRENT_ANNOTATION_VERSION = "3.1"

SAMPLE_QC_VERSIONS = ["3", "3.1"]
CURRENT_SAMPLE_QC_VERSION = "3.1"

VARIANT_QC_VERSIONS = ["3", "3.1"]
CURRENT_VARIANT_QC_VERSION = "3.1"
