"""Script containing version and release constants."""
VERSIONS = ["4.0"]
CURRENT_VERSION = "4.0"

RELEASES = ["4.0"]
CURRENT_RELEASE = "4.0"

COVERAGE_RELEASES = {"exomes": ["4.0"]}
CURRENT_COVERAGE_RELEASE = {"exomes": "4.0"}

HGDP_TGP_RELEASES = ["4.0"]
CURRENT_HGDP_TGP_RELEASE = "4.0"

COMBINED_FAF_RELEASES = ["4.0"]
CURRENT_COMBINED_FAF_RELEASE = "4.0"
