[tool.black]
target-version = ['py36', 'py37', 'py38']
preview = true
exclude = "cuKING"
[tool.isort]
profile = "black"
skip = "cuKING"
[tool.autopep8]
# Use same max line length as the default in Black - 88
max_line_length = 88
# Ignore errors that conflict with Black
# E201 - whitespace after ‘(‘
# E202 - whitespace before ‘)’
# E203 - whitespace before ‘:’
# Ignore E731 - do not assign a lambda expression, use a def
# Ignore W605 - invalid escape sequence
ignore = ['E201', 'E202', 'E203', 'E731', 'W605']
recursive = true
aggressive = 1
exclude = "cuKING"
