"""Script containing sample QC related resources."""

from gnomad.resources.resource_utils import TableResource, VersionedTableResource

from gnomad_qc.v4.resources.constants import (
    CURRENT_SAMPLE_QC_VERSION,
    SAMPLE_QC_VERSIONS,
)


def get_sample_qc(
    strat: str = "all", test: bool = False, data_type: str = "exomes"
) -> VersionedTableResource:
    """
    Get sample QC annotations generated by Hail for the specified stratification.

    Possible values for `strat`:
        - bi_allelic
        - multi_allelic
        - all

    :param strat: Which stratification to return.
    :param test: Whether to use a tmp path for analysis of the test VDS instead of the
        full v4 VDS.
    :param data_type: Data type used in sample QC, e.g. "exomes" or "joint".
    :return: Sample QC table.
    """
    return VersionedTableResource(
        CURRENT_SAMPLE_QC_VERSION,
        {
            version: TableResource(
                f"{get_sample_qc_root(version, test, data_type)}/hard_filtering/gnomad.{data_type}.v{version}.sample_qc_all{'' if strat == 'all' else f'_{strat}'}.ht"
            )
            for version in SAMPLE_QC_VERSIONS
        },
    )
